SELECT ORDER_NO, AFILE, PAINT_NAME, ARTIST_NAME, PAINT_PRICE, ORDER_STATUS FROM BUY_LIST BL 
JOIN PAINT P ON (BL.PAINT_NO = P.PAINT_NO)
JOIN PAINT_PHOTO PP ON (P.PAINT_NO = PP.PAINT_NO)
WHERE USER_ID = 'user01' AND ORDER_DATE  BETWEEN (SYSDATE -30) AND (SYSDATE);

SELECT ORDER_NO, AFILE, PAINT_NAME, ARTIST_NAME, PAINT_PRICE, ORDER_STATUS FROM BUY_LIST BL 
JOIN PAINT P ON (BL.PAINT_NO = P.PAINT_NO)
JOIN PAINT_PHOTO PP ON (P.PAINT_NO = PP.PAINT_NO)
WHERE USER_ID = 'user01' AND ORDER_STATUS = '배송준비중';